# Build workflow

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # [ubuntu-latest, macos-latest, windows-latest] [15, 16-ea]
        os: [ubuntu-latest]
        java: [15]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Checkout tokenproducer repo
        uses: actions/checkout@v2
        with:
          repository: css4j/tokenproducer
          path: tokenproducer

      - name: Checkout carte-util repo
        uses: actions/checkout@v2
        with:
          repository: css4j/carte-util
          path: carte-util

      - name: Checkout xml-dtd repo
        uses: actions/checkout@v2
        with:
          repository: css4j/xml-dtd
          path: xml-dtd

      - name: Checkout css4j repo
        uses: actions/checkout@v2
        with:
          repository: css4j/css4j
          path: css4j

      - name: Checkout css4j-agent repo
        uses: actions/checkout@v2
        with:
          repository: css4j/css4j-agent
          path: css4j-agent

      - name: Checkout css4j-awt repo
        uses: actions/checkout@v2
        with:
          repository: css4j/css4j-awt
          path: css4j-awt

      - name: Checkout css4j-dom4j repo
        uses: actions/checkout@v2
        with:
          repository: css4j/css4j-dom4j
          path: css4j-dom4j

      - name: Setup Java JDK ${{ matrix.java }}
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ matrix.java }}

      - name: Setup Maven
        uses: stCarolas/setup-maven@v1
        with:
          # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
          maven-version: 3.6.3

      - name: download JCLF pom
        uses: wei/curl@v1
        with:
          args: --output jclf-4.1.0.pom https://css4j.github.io/maven/io/sf/jclf/jclf/4.1.0/jclf-4.1.0.pom

      - name: download JCLF jar
        uses: wei/curl@v1
        with:
          args: --output jclf-4.1.0.jar https://sourceforge.net/projects/jclf/files/jclf/4.1.0/jclf-4.1.0.jar/download

      - name: Install JCLF
        run: mvn install:install-file -Dfile=jclf-4.1.0.jar -DpomFile=jclf-4.1.0.pom -DgroupId=io.sf.jclf -DartifactId=jclf -Dversion=4.1.0 -Dpackaging=jar

      - name: Cache Maven packages
        uses: actions/cache@v2.1.1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Runs Maven build
      - name: Maven build
        run: mvn package
