# CI workflow

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  check:
    runs-on: ubuntu-latest

    name: Java 17 ubuntu build

    env:
      HOME: ${{ github.workspace }}
      MAVEN_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/.m2/repository"

    steps:
      # Check-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Verify that the Maven-based install scripts work
      - name: Install JCLF
        run: ./maven/install-jclf.sh

      - name: Install XPP3
        run: ./maven/install-xpp3.sh

      - name: Install CSS4J
        run: ./maven/install-css4j.sh

      - name: Check the JCLF-text install
        run: ls -l ~/.m2/repository/io/sf/jclf/jclf-text

      - name: Check the XMLPull install
        run: ls -l ~/.m2/repository/xmlpull/xmlpull

      - name: Check the XPP3 install
        run: ls -l ~/.m2/repository/xpp3/xpp3_min

      - name: Check the tokenproducer install
        run: ls -l ~/.m2/repository/io/sf/carte/tokenproducer

      - name: Check the carte-util install
        run: ls -l ~/.m2/repository/io/sf/carte/carte-util

      - name: Check the xml-dtd install
        run: ls -l ~/.m2/repository/io/sf/carte/xml-dtd

      - name: Check the css4j install
        run: ls -l ~/.m2/repository/io/sf/carte/css4j

      - name: Check the css4j-agent install
        run: ls -l ~/.m2/repository/io/sf/carte/css4j-agent

      - name: Check the css4j-awt install
        run: ls -l ~/.m2/repository/io/sf/carte/css4j-awt

      - name: Check the css4j-dom4j install
        run: ls -l ~/.m2/repository/io/sf/carte/css4j-dom4j

      # Check the production of Javadocs
      - name: Build modular Javadoc
        run: ./gradlew mergedJavadoc
