# CI workflow

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # [ubuntu-latest, macos-latest, windows-latest] [17, 18-ea]
        os: [ubuntu-latest, windows-latest]
        java: [17]

    name: Java ${{ matrix.Java }} ${{ matrix.os }} build

    env:
      HOME: $GITHUB_WORKSPACE

    steps:
      # Check-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'

      # Validate wrapper to prevent potential supply chain attack
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      # Verify that the Maven-based install scripts work
      - name: Install JCLF
        run: ./maven/install-jclf.sh

      - name: Install XPP3
        run: ./maven/install-xpp3.sh

      - name: Install CSS4J
        run: ./maven/install-css4j.sh

      # Check the production of Javadocs
      - name: Build modular Javadoc
        run: ./gradlew mergedJavadoc
